---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbench-pv-claim-${STORAGE_CLASS}
spec:
  storageClassName: ${STORAGE_CLASS}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${STORAGE_SIZE}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-${STORAGE_CLASS}
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: ${DOCKER_IMAGE}
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          - name: FIO_SIZE
            value: ${FIO_SIZE}
          # - name: DBENCH_QUICK
          #   value: "yes"
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-pv-claim-${STORAGE_CLASS}
  backoffLimit: 4
